services:
  etl:
    image: jokecontainer.azurecr.io/etl
    build:
      context: ./etl
    container_name: etl
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - QUEUE_NAME=MODERATED_JOKES
      - MYSQL_CONTAINER_SERVICE=mysql
      - MYSQL_CONTAINER_USER=${MYSQL_USER}
      - MYSQL_CONTAINER_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_CONTAINER_DATABASE=${MYSQL_DATABASE}
    depends_on:
      - mysql
    ports:
      - 4001:3001

  joke:
    image: jokecontainer.azurecr.io/joke
    build:
      context: ./joke
    container_name: joke
    pull_policy: always
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_CONTAINER_SERVICE=mysql
      - MYSQL_CONTAINER_USER=${MYSQL_USER}
      - MYSQL_CONTAINER_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_CONTAINER_DATABASE=${MYSQL_DATABASE}
    depends_on:
      - mysql
    ports:
      - 4000:3000

  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 4002:3306

volumes:
  mysql_data:
