services:
  rabbitmq-mod:
    image: rabbitmq:3-management
    hostname: rabbitmq # give the cluster a meaningful name
    container_name: rabbitmq-mod
    restart: unless-stopped

    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_USER=root
      - RABBITMQ_PASS=root

    ports:
      - 4101:5672 # Message broker. Make ports same as we won't be accessing from internet
      - 4102:15672 # Management interface. Make ports same as it's meant to be accessed via the internet

    volumes:
      - rabbit-test-prod-vol:/var/lib/rabbitmq/ # Where to store the queued data

  moderate:
    image: jokecontainer.azurecr.io/moderate
    pull_policy: always # Attempt to always pull latest image from docker. Lazy if not using versioning. And slow as up will always pull
    build:
      context: .
    container_name: moderate
    restart: unless-stopped
    environment:
      - PROD_QUEUE=MODERATED_JOKES
      - CON_QUEUE=SUBMITTED_JOKES
    depends_on:
      - rabbitmq-mod
    volumes:
      - typesVolume:/data
    ports:
      - 4100:3100

volumes:
  rabbit-test-prod-vol:
    driver: local
  typesVolume:
    driver: local
